from enum import Enum


class EventType(str, Enum):

    FLIGHT_CREATED = "FLIGHT_CREATED"

    BOARDING_STARTED = "BOARDING_STARTED"

    FINAL_CALL = "FINAL_CALL"

    FLIGHT_DELAYED = "FLIGHT_DELAYED"

    GATE_CHANGED = "GATE_CHANGED"

    FLIGHT_CANCELLED = "FLIGHT_CANCELLED"

    FLIGHT_DEPARTED = "FLIGHT_DEPARTED"

    FLIGHT_ARRIVED = "FLIGHT_ARRIVED"